language: perl

matrix:
  include:
  - perl: "5.30"
  - perl: "5.28"
  - perl: "5.26"
  - perl: "5.24"
  - perl: "5.22"
  - perl: "5.20"
    dist: trusty
  - perl: "5.16"
    dist: trusty
  - perl: "5.26"
    os: osx
    osx_image: xcode7.3

env:
  global:
  - ALIEN_BLOOM_TEST_VERSION="1.6"
  - HARNESS_OPTIONS="j5"

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      eval "$($HOME/perl5/perlbrew/bin/perlbrew env $TRAVIS_PERL_VERSION)"
      export PATH=${PERLBREW_PATH:-$PERLBREW_ROOT/bin}:$PATH
      perlbrew --quiet install-cpanm --force
      cpanm --version
      env | grep -i ^perl
      export SSL_DIR=/usr/local/Cellar/openssl/1.0.2j
    fi
  - cpanm -n -q Sort::Versions HTTP::Tiny
